# Listas, tuplas y conjuntos/colecciones de datos   <a id="lists"></a><a href="#index"><i class="fa fa-list-alt" aria-hidden="true"></i></a>

* [Listas](#listas)
    - [Rebanado de listas](#rebanado-de-listas)
    - [Otras operaciones con listas](#otras-operaciones-con-listas)
    - [Copiado de listas](#copiado-de-listas)
    - [Listas por comprensión](#listas-por-comprension)
* [Tuplas](#tuples)
* [Conjuntos](#sets)
* [Diccionarios](#dictionaries)

# Listas <a id="listas"></a>  <a href="#lists"><i class="fa fa-list-alt"></i></a>

Una <i class="concept">lista</i> es una colección de elementos (no necesariamente del mismo tipo) en las que el orden es relevante. Se delimitan con corchetes y sus elementos se separan por comas.

In [1]:
lista = ["Nilo", [23, 34.45], -2+4j] # Se pueden mezclar tipos
lista

['Nilo', [23, 34.45], (-2+4j)]

In [2]:
ríos = ["Nilo", "Arlanza", "Cerezo", "Pico", "Vena" ]
print(ríos)
print(len(ríos))

['Nilo', 'Arlanza', 'Cerezo', 'Pico', 'Vena']
5


Se puede acceder a los elementos de una lista utilizando un índice el índice del primer elemento es 0-

In [3]:
print(ríos[1]) # => 'Arlanza', dado que los índices empiezan en 0
print(ríos[0]) # => 'Nilo'
# Para obtener el último de los elementos
último = len(ríos)-1
print(ríos[último]) 
print(ríos[-1]) # Usando números negativos, se pueden indexar elementos desde el final 

Arlanza
Nilo
Vena
Vena


 ¡Cuidado!</span> Utilizar un índice mayor o igual que la longitud de la lista dará un error. 

In [4]:
# print(ríos[11]) # => Error! index out of range

Se pueden añadir elementos al final de una lista con el método `append`.

In [5]:
ríos.append("Duero")
print(ríos)

['Nilo', 'Arlanza', 'Cerezo', 'Pico', 'Vena', 'Duero']


Se pueden insertar elementos en posiciones arbitrarias con el método `insert`.

In [6]:
antes_de_esta_posición = 0
print(ríos)
ríos.insert(antes_de_esta_posición, "Colorado")
print(ríos)

['Nilo', 'Arlanza', 'Cerezo', 'Pico', 'Vena', 'Duero']
['Colorado', 'Nilo', 'Arlanza', 'Cerezo', 'Pico', 'Vena', 'Duero']


In [7]:
antes_de_esta_posición = -1 # con posiciones negativas, comenzamos por el final
print(ríos)
ríos.insert(antes_de_esta_posición, "Danubio") 
print(ríos)

['Colorado', 'Nilo', 'Arlanza', 'Cerezo', 'Pico', 'Vena', 'Duero']
['Colorado', 'Nilo', 'Arlanza', 'Cerezo', 'Pico', 'Vena', 'Danubio', 'Duero']


<span class="label label-danger"><i class="fa fa-bomb" aria-hidden="true"></i> ¡Cuidado!</span> Si lo que se inserta es a su vez una lista, la lista insertada aparece como nuevo elemento (recuerda, los elementos de una lista pueden ser de tipos arbitrarios, incluidas las listas).

In [8]:
ríos = ["Nilo", "Arlanza", "Cerezo", "Pico", "Vena" ]
más_ríos = ["Danubio", ["Ebro"], "Turia" ]
print(ríos)
ríos.insert(2, más_ríos)
print(ríos)

['Nilo', 'Arlanza', 'Cerezo', 'Pico', 'Vena']
['Nilo', 'Arlanza', ['Danubio', ['Ebro'], 'Turia'], 'Cerezo', 'Pico', 'Vena']


Como ahora uno de los elementos es una lista, se pueden concatenar la indexación para acceder a los elementos de la sublista.

In [9]:
ríos[2]

['Danubio', ['Ebro'], 'Turia']

In [10]:
ríos[2][1][0]

'Ebro'

Se pueden combinar listas con el operador `+`.

In [11]:
ríos = ["Nilo", "Arlanza", "Cerezo", "Pico", "Vena" ]
más_ríos = ["Oca", "Danubio", "Ebro", "Guadalmedina", "Eo" ]
ríos = ríos + más_ríos
print(ríos)

['Nilo', 'Arlanza', 'Cerezo', 'Pico', 'Vena', 'Oca', 'Danubio', 'Ebro', 'Guadalmedina', 'Eo']


In [12]:
ríos = ["Nilo", "Arlanza", "Cerezo", "Pico", "Vena" ]
más_ríos = ["Oca", "Danubio", "Ebro", "Guadalmedina", "Eo" ]
ríos += más_ríos
print(ríos)

['Nilo', 'Arlanza', 'Cerezo', 'Pico', 'Vena', 'Oca', 'Danubio', 'Ebro', 'Guadalmedina', 'Eo']


El operador **+** concatena listas, el método **.insert** inserta un nuevo elemento, si éste es una lista, la lista aparecerá como un elemento dentro de la otra lista.


Si tenemos una lista de números, podemos sumar sus elementos (función `sum`), o encontrar el máximo (función `max`), o encontrar el mínimo (función `min`).

In [13]:
nums = [5, 7, 9, 2]
print(sum(nums))
print(max(nums))
print(min(nums))

23
9
2


<span class="label label-danger"><i class="fa fa-bomb" aria-hidden="true"></i> ¡Cuidado!</span>
Las funciones `max` y `min` funcionan tanto si se les pasa un **número variables de argumentos**, como si se les pasa una **colección**, pero la función `sum` sólo funciona cuando se le pasa como único argumento una colección.

In [14]:
max(5, 7, 9, 2)

9

In [15]:
# Da error
#sum(5, 7, 9, 2)

<div class="alert alert-info">
   <i style="font-size: larger;" class="fa fa-info-circle" aria-hidden="true"></i> Podemos comprobar si un elemento está dentro de una lista (<b>o dentro de cualquier colección</b>) utilizando el operador <code>in</code>.
</div>


In [16]:
print("Cerezo" in ríos)
print("Bernesga" in ríos)

True
False


In [17]:
ríos

['Nilo',
 'Arlanza',
 'Cerezo',
 'Pico',
 'Vena',
 'Oca',
 'Danubio',
 'Ebro',
 'Guadalmedina',
 'Eo']

Se pueden eliminar elementos con el operador `del`.

In [18]:
del ríos[ríos.index('Guadalmedina')] # .index devuelve el índice de su argumento en la lista
ríos

['Nilo', 'Arlanza', 'Cerezo', 'Pico', 'Vena', 'Oca', 'Danubio', 'Ebro', 'Eo']

In [19]:
del ríos[0], ríos[1] # Ojo, se aplican en secuencia y eso afecta a los índices

In [20]:
ríos

['Arlanza', 'Pico', 'Vena', 'Oca', 'Danubio', 'Ebro', 'Eo']

Los elementos de una lista se pueden cambiar cuando la lista aparece a la izquierda de una asignación.

In [21]:
ríos[0] = 'El río Arlanza'

In [22]:
ríos

['El río Arlanza', 'Pico', 'Vena', 'Oca', 'Danubio', 'Ebro', 'Eo']

En vez de un único elemento, podemos reemplazar (**y borrar**) varios usando rebanadas (en la siguiente sección).

In [23]:
ríos[3:5] = ['A', 'B']

In [24]:
ríos

['El río Arlanza', 'Pico', 'Vena', 'A', 'B', 'Ebro', 'Eo']

In [25]:
del ríos[1:3]

In [26]:
ríos

['El río Arlanza', 'A', 'B', 'Ebro', 'Eo']

## Rebanado de listas   <a id="rebanado-de-listas"></a>    <a href="#lists"><i class="fa fa-list-alt" aria-hidden="true"></i></a>
El rebanado (que ya habíamos visto con cadenas para obtener subcadenas) se puede aplicar también a listas.

En las listas el rebanado permite obtener una sublista utilizando los índices de inicio y fin de los elementos que quiere extraerse; adicionalmente se puede indicar un paso para extraer elementos no consecutivos.

In [27]:
mi_lista = [0, 1, 2, 3, 4, 5, 6, 7, 8, 9]
print(mi_lista[3:8])
print(mi_lista[8:2])
print(mi_lista[1:9:3])

[3, 4, 5, 6, 7]
[]
[1, 4, 7]


<div class="alert alert-info">
   <i style="font-size: larger;" class="fa fa-info-circle" aria-hidden="true"></i> También se pueden utilizar índices y pasos negativos.
</div>


In [28]:
mi_lista = [0, 1, 2, 3, 4, 5, 6, 7, 8, 9]
        #   0, 1, 2, 3, 4, 5, 6, 7, 8, 9   # índices desde el inicio
        # -10,-9,-8,-7,-6,-5,-4,-3,-2,-1   # índices desde el final

In [29]:
print(mi_lista[-4:])
print(mi_lista[-7:-2])
print(mi_lista[3:-2])
print(mi_lista[-7:8])
print(mi_lista[2:-1:2])
print(mi_lista[-1:2:-1])

[6, 7, 8, 9]
[3, 4, 5, 6, 7]
[3, 4, 5, 6, 7]
[3, 4, 5, 6, 7]
[2, 4, 6, 8]
[9, 8, 7, 6, 5, 4, 3]


<div class="alert alert-info">
   <i style="font-size: larger;" class="fa fa-info-circle" aria-hidden="true"></i> Como con las rebanadas de cadenas, se pueden omitir los índices de inicio, del final, o ambos.
</div>


In [30]:
mi_lista[4:]

[4, 5, 6, 7, 8, 9]

In [31]:
mi_lista[:5]

[0, 1, 2, 3, 4]

In [32]:
mi_lista[:-6]

[0, 1, 2, 3]

In [33]:
mi_lista[::3]

[0, 3, 6, 9]

In [34]:
mi_lista[::-1]

[9, 8, 7, 6, 5, 4, 3, 2, 1, 0]

In [35]:
mi_lista[:] # Copy of list!

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

## Otras operaciones con listas  <a id="otras-operaciones-con-listas"></a>    <a href="#lists"><i class="fa fa-list-alt"></i></a>

Otras formas de modificar listas.

In [36]:
ríos = ['Ebro', 'Oca', 'Pico', 'Nilo', 'Arlanza',
        'Guadalmedina', 'Vena', 'Cerezo']
print(ríos)
ríos.remove("Guadalmedina")
print(ríos)

['Ebro', 'Oca', 'Pico', 'Nilo', 'Arlanza', 'Guadalmedina', 'Vena', 'Cerezo']
['Ebro', 'Oca', 'Pico', 'Nilo', 'Arlanza', 'Vena', 'Cerezo']


In [37]:
print(ríos)
ríos.pop(-2)
print(ríos)

['Ebro', 'Oca', 'Pico', 'Nilo', 'Arlanza', 'Vena', 'Cerezo']
['Ebro', 'Oca', 'Pico', 'Nilo', 'Arlanza', 'Cerezo']


In [38]:
print(ríos)
un_río = ríos.pop()
print(ríos)
print(un_río)

['Ebro', 'Oca', 'Pico', 'Nilo', 'Arlanza', 'Cerezo']
['Ebro', 'Oca', 'Pico', 'Nilo', 'Arlanza']
Cerezo


In [39]:
# [].pop() # => pop de lista vacía, SyntaxError

In [40]:
print(ríos.index("Arlanza"))

4


Cambiar el orden de las listas.

In [41]:
ríos = ['Arlanza', 'Pico', 'Vena', 'Oca',
        'Danubio', 'Ebro', 'Guadalmedina', 'Eo']
ríos.reverse()
print(ríos)
print(ríos[::-1])

['Eo', 'Guadalmedina', 'Ebro', 'Danubio', 'Oca', 'Vena', 'Pico', 'Arlanza']
['Arlanza', 'Pico', 'Vena', 'Oca', 'Danubio', 'Ebro', 'Guadalmedina', 'Eo']


In [42]:
print(ríos)
res = sorted(ríos)
print(res)
print(ríos) # La lista original no se ve afectada

['Eo', 'Guadalmedina', 'Ebro', 'Danubio', 'Oca', 'Vena', 'Pico', 'Arlanza']
['Arlanza', 'Danubio', 'Ebro', 'Eo', 'Guadalmedina', 'Oca', 'Pico', 'Vena']
['Eo', 'Guadalmedina', 'Ebro', 'Danubio', 'Oca', 'Vena', 'Pico', 'Arlanza']


In [43]:
res = ríos.sort() 
print(ríos) # Se ordena la lista original 
print(res)  # El valor devuelto es None

['Arlanza', 'Danubio', 'Ebro', 'Eo', 'Guadalmedina', 'Oca', 'Pico', 'Vena']
None


In [44]:
ríos.sort(reverse=True)
print(ríos)

['Vena', 'Pico', 'Oca', 'Guadalmedina', 'Eo', 'Ebro', 'Danubio', 'Arlanza']


In [45]:
print(sorted(ríos, key=len))

['Eo', 'Oca', 'Vena', 'Pico', 'Ebro', 'Danubio', 'Arlanza', 'Guadalmedina']


## Copiado de listas

Vamos a analizar con algo más de detalle que ocurre cuando se usa `[:]`. Primero vamos una asignación de una lista a una nueva variable.

In [46]:
mi_lista = [0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [47]:
otra_lista = mi_lista # Ahora tenemos dos «nombres» para la lista: otra_lista y mi_lista
otra_lista

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [48]:
mi_lista[0] = 'cero'
mi_lista

['cero', 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [49]:
otra_lista

['cero', 1, 2, 3, 4, 5, 6, 7, 8, 9]

Ahora asignamos, pero usando `[:]`. 

In [50]:
mi_lista = [0, 1, ['dos', 'tres'], 4, 5, 6]

In [51]:
otra_lista = mi_lista[:]
print(mi_lista)
print(otra_lista)

[0, 1, ['dos', 'tres'], 4, 5, 6]
[0, 1, ['dos', 'tres'], 4, 5, 6]


Las dos variables parecen tener la misma lista, en realidad tienen dos listas que son iguales, que no es exactamente lo mismo. Comprobemos que efectivamente esto es así, modificando una de las listas.

In [52]:
mi_lista[0] = 'cero'
mi_lista

['cero', 1, ['dos', 'tres'], 4, 5, 6]

Hemos modificado `mi_lista`, sin embargo, la lista en `otra_lista` no se ha visto aceptada.

In [53]:
otra_lista

[0, 1, ['dos', 'tres'], 4, 5, 6]

Bueno, en realidad, esta no es toda la historia. Resulta que las dos listas comparten un elemento. La sublista que aparece como tercer elemento es la misma en ambas.

In [54]:
mi_lista[2]

['dos', 'tres']

In [55]:
mi_lista[2][1] = 'THREE'
mi_lista

['cero', 1, ['dos', 'THREE'], 4, 5, 6]

In [56]:
otra_lista

[0, 1, ['dos', 'THREE'], 4, 5, 6]

Usando el método `.copy()`, pero también sucede lo mismo con una lista anidada

In [57]:
mi_lista = [0, 1, ['dos', 'tres'], 4, 5, 6]
otra_lista = mi_lista.copy()
print(mi_lista)
print(otra_lista)

[0, 1, ['dos', 'tres'], 4, 5, 6]
[0, 1, ['dos', 'tres'], 4, 5, 6]


In [58]:
mi_lista[2][1] = 'THREE'
print(mi_lista)
print(otra_lista)

[0, 1, ['dos', 'THREE'], 4, 5, 6]
[0, 1, ['dos', 'THREE'], 4, 5, 6]


## Listas por comprensión <a id="listas-por-comprension"></a>    <a href="#lists"><i class="fa fa-list-alt"></i></a>

<div class="alert alert-info" style="text-indent:-.65em; padding-left: 2.2em">
   <i style="font-size: larger;" class="fa fa-info-circle" aria-hidden="true"></i> La definición de listas por compresión es una característica muy potentes de Python. Entender su funcionamiento puede ayudarnos a simplificar enormemente nuestro código. 
</div>


In [59]:
nums = [5, 2, 7, 8, 9, 4]
print([ n*10 for n in nums ])
print([ n*10 for n in nums if n%2 ])
print([ n*10 for n in nums if not n%2 ])

[50, 20, 70, 80, 90, 40]
[50, 70, 90]
[20, 80, 40]


In [60]:
ríos = ["Nilo", "Arlanza", "Cerezo", "Pico", "Vena" ]
print([ (n, r) for n, r in enumerate(sorted(ríos)) ])
print([ (n, r) for n, r in enumerate(sorted(ríos), start=1) ])
print('\n'.join([ str(n) + '. ' + r for n, r in enumerate(sorted(ríos), start=1) ]))

[(0, 'Arlanza'), (1, 'Cerezo'), (2, 'Nilo'), (3, 'Pico'), (4, 'Vena')]
[(1, 'Arlanza'), (2, 'Cerezo'), (3, 'Nilo'), (4, 'Pico'), (5, 'Vena')]
1. Arlanza
2. Cerezo
3. Nilo
4. Pico
5. Vena


`enumerate()` se aplica a una lista (en general a un objeto iterable) para poder obtener una secuencia de pares constituidos por los elementos de la lista junto con el orden de éstos.

# Tuplas <a id="tuples"></a>    <a href="#lists"><i class="fa fa-list-alt"></i></a>
Las <i class="concept">tuplas</i> son como listas, pero no se pueden modificar, es decir, una vez que se crean, sus valores no pueden cambiarse. Esto último permite que las tuplas pueden usarse como claves de diccionarios (que se verán <a href="#dictionaries">más adelante</a>), en cambio las listas no.
```python
["Esto", "es", "una", "lista"]
("Esto", "es", "una", "tupla")
```

Una de las ventajas de las tuplas es que son mucho más rápidas.

In [61]:
%%timeit
lista = [0, 1, 2, 3, 4, 5, 6, 7, 8, 9] # se muestra el mejor resultado de 7 ejecuciones

41.5 ns ± 0.892 ns per loop (mean ± std. dev. of 7 runs, 10,000,000 loops each)


In [62]:
%%timeit
tupla = (0, 1, 2, 3, 4, 5, 6, 7, 8, 9)

8.61 ns ± 0.106 ns per loop (mean ± std. dev. of 7 runs, 100,000,000 loops each)


<span class="label label-danger"><i class="fa fa-bomb" aria-hidden="true"></i> ¡Cuidado!</span> la evaluación de la siguiente celda dará error, dado que las tuplas, una vez creadas, no pueden modificarse.

In [63]:
#tupla[0] = 'Pico' # => TypeError: 'tuple' object does not support item assignment

Más ejemplos de cosas que pueden hacerse con tuplas:

Recuerda que una cadena de la forma *`f"···"`* es una **cadena de formato** o **cadena-f**. Dentro de una cadena de formato las expresiones encerradas entre llaves **{·}** se evaluan antes de imprimir la cadena. A este proceso de mezclar porciones literales y expresiones que se evaluan se le conoce como <a href="https://es.qwe.wiki/wiki/String_interpolation"><b class="concept">interpolación de cadenas</b></a>.


In [64]:
a, b = 1, 2     # inicialización simultánea de varias variables.
print(f"a: {a}, b: {b}")
a, b = b, a     # intercambio de valores de variables
print(f"a: {a}, b: {b}")
a, _ = 12, 13   # recuperación de valores de una tupla, ignorando los que no interesan

a: 1, b: 2
a: 2, b: 1


<span class="label label-danger"><i class="fa fa-bomb" aria-hidden="true"></i> ¡Cuidado!</span> la evaluación de la siguiente celda dará error, dado que a la izquierda hay más variables que valores a la derecha.

In [65]:
#a, b, c = (1, 2) # => ValueError: not enough values to unpack (expected 3, got 2)

<span class="label label-danger"><i class="fa fa-bomb" aria-hidden="true"></i> ¡Cuidado!</span> la evaluación de la siguiente celda dará error, dado que a la izquierda hay menos variables que valores a la derecha.

In [66]:
# a, b = 1, 2, 3 # => ValueError: too many values to unpack (expected 2)

<span class="label label-danger"><i class="fa fa-bomb" aria-hidden="true"></i> ¡Cuidado!</span> Si se quiere tener una tupla de un elemento, es necesario utilizar una coma tras ese elemento, aunque no haya un segundo.

In [67]:
t1 = ((1))
t2 = (1,)
print(f"type(t1): {type(t1)}")
print(f"type(t2): {type(t2)}")
print(f"t1: {t1}")
print(f"t2: {t2}")

type(t1): <class 'int'>
type(t2): <class 'tuple'>
t1: 1
t2: (1,)


<div class="alert alert-info">
   <i style="font-size: larger;" class="fa fa-info-circle" aria-hidden="true"></i> Las asignaciones con «desempaquetado» se pueden hacer también para listas y con anidamientos de elementos más complejas.
</div>

In [68]:
[a, [b, c]] = [1, [2, 3]]
a, b, c

(1, 2, 3)

In [69]:
[a, b] = (1, [2, 3])
a, b

(1, [2, 3])

In [70]:
a, (b,c) = [1, [2, 3]]
a, b, c

(1, 2, 3)

In [71]:
a, b = [1, [2, 3]]
a, b

(1, [2, 3])

# Conjuntos <a id="sets"></a>   <a href="#lists"><i class="fa fa-list-alt"></i></a>

Los <i class="concept">conjuntos</i> son colecciones de objetos en las que el orden no es relevante y donde no se permiten duplicados.

Se pueden modificar (aunque existe una versión no modificable, los 
 <a href="https://docs.python.org/3/library/stdtypes.html#frozenset">frozenset</a>). 

La comprobación de que un elemento pertenece a un conjunto (operador `in`) es más eficiente y rápida que la comprobación 
de que un elemento pertenece a una lista.

Solo se pueden utilizar conjuntos de elementos de tipos inmutables.


In [72]:
ríos = { "Nilo", "Arlanza", "Cerezo", "Pico", "Vena", "Nilo", "Cerezo" }
print(ríos) # El orden no tiene porque coincidir con el utilizado en la definición
print(type(ríos))
# Tomamos el elemento del conjunto con pop
print(ríos.pop())
print(ríos)

{'Arlanza', 'Nilo', 'Vena', 'Cerezo', 'Pico'}
<class 'set'>
Arlanza
{'Nilo', 'Vena', 'Cerezo', 'Pico'}


### Operaciones con conjuntos <a id="setsOperators"></a>   <a href="#lists"><i class="fa fa-list-alt"></i></a>

Con el tipo de datos `set` se pueden hacer las mismas operaciones que con los conjuntos matemáticos: intersección, diferencia, unión, comprobación de pertenencia, etcétera

In [73]:
unos_ríos = { "Nilo", "Arlanza", "Cerezo", "Pico", "Misisipi" } # A
otros_ríos = { "Nilo", "Danubio", "Cerezo" }                    # B
otros_ríos.add("Bernesga")                                      # A ∪ {e} 
unos_ríos.remove("Misisipi")                                    # A - {e}
unos_ríos, otros_ríos                                           # A, B

({'Arlanza', 'Cerezo', 'Nilo', 'Pico'},
 {'Bernesga', 'Cerezo', 'Danubio', 'Nilo'})

In [74]:
"Bernesga" in otros_ríos  # ¿e ∊ A?

True

In [75]:
A = {1, 2, 3}; B = {2, 3, 4}
A.symmetric_difference(B)

{1, 4}

In [76]:
# A.symmetric_difference(B) también puede hacer con el operador `^``
A ^ B 

{1, 4}

In [77]:
unos_ríos, otros_ríos    # A, B

({'Arlanza', 'Cerezo', 'Nilo', 'Pico'},
 {'Bernesga', 'Cerezo', 'Danubio', 'Nilo'})

In [78]:
unos_ríos & otros_ríos    # A ∩ B

{'Cerezo', 'Nilo'}

In [79]:
print(unos_ríos.isdisjoint(otros_ríos))  # ¿A ∩ B == ∅?
print(unos_ríos.issubset(otros_ríos))    # ¿A ⊆ B?
print(unos_ríos.issuperset(otros_ríos))  # ¿A ⊇ B?

False
False
False


In [80]:
# También se pueden usar operadores para isdisjoint, issubset, issuperset
print(unos_ríos & otros_ríos == set())  # ¿A ∩ B == ∅?
print(unos_ríos <= otros_ríos)          # ¿A ⊆ B?
print(unos_ríos >= otros_ríos)          # ¿A ⊇ B?

False
False
False


In [81]:
unos_ríos, otros_ríos    # A, B

({'Arlanza', 'Cerezo', 'Nilo', 'Pico'},
 {'Bernesga', 'Cerezo', 'Danubio', 'Nilo'})

In [82]:
print(unos_ríos.difference(otros_ríos))           # A - B
print(otros_ríos.difference(unos_ríos))           # B - A
print(unos_ríos.symmetric_difference(otros_ríos)) # A ∆ B

{'Arlanza', 'Pico'}
{'Bernesga', 'Danubio'}
{'Danubio', 'Bernesga', 'Pico', 'Arlanza'}


In [83]:
# Mismas operaciones que en la celda previa, pero usando operadores
print(unos_ríos - otros_ríos)  # A - B
print(unos_ríos ^ otros_ríos)  # A ∆ B

{'Arlanza', 'Pico'}
{'Danubio', 'Bernesga', 'Pico', 'Arlanza'}


In [84]:
unos_ríos, otros_ríos    # A, B

({'Arlanza', 'Cerezo', 'Nilo', 'Pico'},
 {'Bernesga', 'Cerezo', 'Danubio', 'Nilo'})

In [85]:
unión = unos_ríos.union(otros_ríos)               # A ∪ B
intersección = unos_ríos.intersection(otros_ríos) # A ∩ B
unión, intersección

({'Arlanza', 'Bernesga', 'Cerezo', 'Danubio', 'Nilo', 'Pico'},
 {'Cerezo', 'Nilo'})

In [86]:
# Mismas operaciones que en la celda previa, pero usando operadores
(unos_ríos | otros_ríos), (unos_ríos & otros_ríos)    # A ∪ B, A ∩ B

({'Arlanza', 'Bernesga', 'Cerezo', 'Danubio', 'Nilo', 'Pico'},
 {'Cerezo', 'Nilo'})

In [87]:
# A ∪ B - A ∩ B == A ∆ B
unión.difference(intersección), unos_ríos.symmetric_difference(otros_ríos)

({'Arlanza', 'Bernesga', 'Danubio', 'Pico'},
 {'Arlanza', 'Bernesga', 'Danubio', 'Pico'})

# Diccionarios (colecciones indexadas por nombre)   <a id="dictionaries"></a><a href="#index"><i class="fa fa-list-alt" aria-hidden="true"></i></a>

Los <i class="concept">diccionarios</i> son estructuras de datos en las que los elementos constituyentes se pueden recuperar utilizando claves que no tienen porque ser valores numéricos, como ocurre con las listas y las tuplas. **Las claves de acceso pueden ser cualquier valor _inmutable_**, aunque lo más habitual es usar cadenas.

Como en los conjuntos, **el orden no es relevante** en los diccionarios.

Se delimitan con llaves (como los conjuntos), sus elementos se separan por comas (como en las listas y los conjuntos), pero éstos consisten en pares <i class="concept">clave</i> y <i class="concept">valor</i> (la clave separada del valor por dos puntos `:`). Los valores pueden ser de tipos arbitrarios y distintos para cada par. Las claves tienen que ser <a href="https://docs.python.org/2/glossary.html#term-hashable"><i class="concept">hashables</i></a>. Un elemento es *hashable* (o *resumible*) si se le puede asignar un valor <i>hash</i> que no cambie en el tiempo de vida del elemento. Un <a href="https://es.wikipedia.org/wiki/Funci%C3%B3n_hash">valor de <i>hash</i></a> es una especie de <i>firma</i> que se puede asociar al elemento, que depende de su valor y que será único para ese elemento. Todos los tipos inmutables de Python son <i>hashables</i>. Los contenedores mutables, como las listas y diccionarios, no lo son.

In [88]:
un_río = {'nombre': 'Nilo', 'longitud': 6853, # km
          'ciudades': ['El Cairo', 'Jartum', 'Jinja', 'Yuba']}

In [89]:
# También podemos pasar una **secuencia** de pares clave/valor al constructor de diccionarios
un_río = dict([('nombre', 'Nilo'), ('longitud', 6853), # km
               ('ciudades', ['El Cairo', 'Jartum', 'Jinja', 'Yuba'])])

El acceso a los elementos se hace con la misma sintaxis que en las listas, pero ahora en vez de un índice se utiliza el valor de la clave del elemento que quiere recuperarse o modificarse.

In [90]:
print(f"nombre del río: {un_río['nombre']}")
print(f"ciudades por las que pasa: {un_río['ciudades']}")

nombre del río: Nilo
ciudades por las que pasa: ['El Cairo', 'Jartum', 'Jinja', 'Yuba']


Si se utiliza una clave de acceso no existente en el diccionario, se genera un error..

In [91]:
# Da error
#print(f"su caudal es: {un_río['caudal']}") # => KeyError: 'caudal' 

<span class="label label-info"><i class="fa fa-info-circle" aria-hidden="true"></i> Truco</span> Si quieres evitar el error de utilizar una clave inexistente, puedes utilizar el método `get` cuyo segundo valor será devuelto en caso de que la clave no exista en el diccionario.

In [92]:
print(f"su caudal es: {un_río.get('caudal')}")
print(f"su caudal es: {un_río.get('caudal', 'eso no lo sé')}")

su caudal es: None
su caudal es: eso no lo sé


La modificación de los valores se hace como en la lista, pero usando la clave como valor de acceso.

In [93]:
un_río['caudal'] = 2.830 # m^3/s , valor erróneo!!! el Nilo tiene un caudal mucho mayor
print(un_río)

{'nombre': 'Nilo', 'longitud': 6853, 'ciudades': ['El Cairo', 'Jartum', 'Jinja', 'Yuba'], 'caudal': 2.83}


Se pueden modificar varios elementos usando el método `update`.

In [94]:
un_río.update({'caudal': 2830, 'afluentes': ['Nilo blanco', 'Nilo azul',
    'Ora', 'Gumara', 'Dinder', 'Sobat', '...']})
print(f"lo que sé de este río es: {un_río}")

lo que sé de este río es: {'nombre': 'Nilo', 'longitud': 6853, 'ciudades': ['El Cairo', 'Jartum', 'Jinja', 'Yuba'], 'caudal': 2830, 'afluentes': ['Nilo blanco', 'Nilo azul', 'Ora', 'Gumara', 'Dinder', 'Sobat', '...']}


Se pueden eliminar un elemento usando el **operador** `del`.

In [95]:
del un_río['afluentes']
print(un_río)

{'nombre': 'Nilo', 'longitud': 6853, 'ciudades': ['El Cairo', 'Jartum', 'Jinja', 'Yuba'], 'caudal': 2830}


In [96]:
un_río.keys(), un_río.values()

(dict_keys(['nombre', 'longitud', 'ciudades', 'caudal']),
 dict_values(['Nilo', 6853, ['El Cairo', 'Jartum', 'Jinja', 'Yuba'], 2830]))

In [97]:
print(type(un_río.keys()), type(un_río.values()))

<class 'dict_keys'> <class 'dict_values'>


In [98]:
print(un_río.items())
print(type(un_río.items()))

dict_items([('nombre', 'Nilo'), ('longitud', 6853), ('ciudades', ['El Cairo', 'Jartum', 'Jinja', 'Yuba']), ('caudal', 2830)])
<class 'dict_items'>


Estos tres últimos métodos: <kbd>keys</kbd>, <kbd>values</kbd> y <kbd>items</kbd>, van a ser muy útiles en combinación con las estructuras de bucle.

# Vectores, matrices y tensores  <a id="arrays"></a><a href="#index"><i class="fa fa-list-alt" aria-hidden="true"></i></a>

En Python no existen tipos específicos para los <i class="concept">vectores</i>, las <i class="concept">matrices</i> y los <i class="concept">tensores</i>. Los vectores son fácilmente representables como listas, las matrices podrían representarse como listas de listas, y del mismo modo los tensores de más dimensiones podrían representarse como listas de tensores de dimensiones menores. Pero el acceso a los elementos usando esta representación se hace un poco engorroso. Además tendríamos que programar las operaciones para manipular estos objetos: sumas, productos, traspuestas, inversas, ...

<div class="alert alert-info" style="text-indent:-.65em; padding-left: 2.2em">
   <i style="font-size: larger;" class="fa fa-info-circle" aria-hidden="true"></i> Un <a href="https://en.wikipedia.org/wiki/Tensor"><i class="concept">tensor</i></a> es un conjunto de valores ordenados en varias dimensiones, arreglo multi dimensional de valores, de modo que se puede hacer referencia a cada valor en la colección (el arreglo) usando las coordenadas que ocupa el valor en la ordenación. Una <a href="https://es.wikipedia.org/wiki/Matriz_(matem%C3%A1ticas)"><i class="concept">matriz</i></a> es un caso especial de tensor de dimensión 2. Un <a href="https://es.wikipedia.org/wiki/Vector"><i class="concept">vector</i></a> es un caso especial de tensor de dimensión 1.
</div>


In [99]:
# Un ejemplo de vectores
v1 = [7, 9, 6]
v2 = [-1, -3, 0]
# La suma de vectores
v_suma = [v1[0]+v2[0], v1[1]+v2[1], v1[2]+v2[2]] # MÉTODO AVANZADO: v_suma = [e1+e2 for e1, e2 in zip(v1, v2)]
print(f"v_suma => {v_suma}")

# Un ejemplo de matriz
M = [[2, 3], [4, 5]]
print(f"M => {M}")
# Accediendo a un elemento de M
print(f"M[0][1] => {M[0][1]}")

# Un ejemplo de tensor
M1 = [[2, 3, 1], [4, 5, -2]]
M2 = [[3, -1, 69], [0, 1, -1]]
T = [M1, M2]
print(f"T => {T}")
# Accediendo a un elemento de T
print(f"T[1][0][2] => {T[1][0][2]}")

v_suma => [6, 6, 6]
M => [[2, 3], [4, 5]]
M[0][1] => 3
T => [[[2, 3, 1], [4, 5, -2]], [[3, -1, 69], [0, 1, -1]]]
T[1][0][2] => 69


Para facilitar un poco la utilización de este tipo de objetos existe la biblioteca [Numpy](http://www.numpy.org/).

Numpy ofrece el tipo `array` que se puede utilizar para representar tensores de dimensiones arbitrarias (también tiene el tipo `matrix` para los tensores bi-dimensionales, [_aunque su uso_](https://stackoverflow.com/questions/4151128/what-are-the-differences-between-numpy-arrays-and-matrices-which-one-should-i-u)
[_se desaconseja_](https://docs.scipy.org/doc/numpy/user/numpy-for-matlab-users.html#array-or-matrix-which-should-i-use)).

Para poder utilizar estos tipos, lo único que tenemos que hacer es importar el paquete `numpy`. Además, la tradición establecida es renombrarlo a `np` para ahorrarnos pulsaciones de teclado.

In [100]:
import numpy as np # Esto importa la biblioteca `numpy` con el nombre `np`

Ahora podemos utilizar toda la funcionalidad que proporcionan `numpy`, lo que nos permitirá manipular tensores como si fueran tipos básicos.

In [101]:
# Un ejemplo de vectores
v1 = np.array([7, 9, 6])
v2 = np.array([-1, -3, 0])
# La suma de vectores
v_suma = v1 + v2
print(f"v_suma => {v_suma}")

v_suma => [6 6 6]


In [102]:
# Un ejemplo de matriz
M = np.array([[2, 3], [4, 5]])
print(f"M =>\n{M}")
# Accediendo a un elemento de M
print(f"M[0, 1] => {M[0, 1]}")

M =>
[[2 3]
 [4 5]]
M[0, 1] => 3


In [103]:
# Un ejemplo de tensor
t1 = [[2, 3, 1], [4, 5, -2]]
t2 = [[3, -1, 69], [0, 1, -1]]
T = np.array([t1, t2])
print(f"T =>\n {T}")
# Accediendo a un elemento de T
print(f"T[1, 0, 2] => {T[1, 0, 2]}")
print(f"T[1][0][2] => {T[1][0][2]}")    # También se puede acceder así

T =>
 [[[ 2  3  1]
  [ 4  5 -2]]

 [[ 3 -1 69]
  [ 0  1 -1]]]
T[1, 0, 2] => 69
T[1][0][2] => 69


**Truco:** Un importante concepto en Numpy es el de [<i class="concept">broadcasting</i>](https://docs.scipy.org/doc/numpy-1.13.0/user/basics.broadcasting.html), básicamente consiste en que cuando se combina con un operador dos <i>arrays</i>, las dimensiones del <i>array</i> de menos dimensiones se transforman para hacerlo compatible con el del mayor dimensión.

In [104]:
M = np.array([[-2, 3], [4, -5], [2, 3]])
v = np.array([[2, 3]])
print(f"M + 10 =>\n {M + 10}")
print(f"M * 5 =>\n {M * 5}")
print(f"M - v =>\n {M - v}")

M + 10 =>
 [[ 8 13]
 [14  5]
 [12 13]]
M * 5 =>
 [[-10  15]
 [ 20 -25]
 [ 10  15]]
M - v =>
 [[-4  0]
 [ 2 -8]
 [ 0  0]]


In [105]:
print(f"M =>\n {M}")
print(f"M == 2 =>\n {M == 2}")
print(f"M > 2 =>\n {M > 2}")
print(f"M == v =>\n {M == v}")

M =>
 [[-2  3]
 [ 4 -5]
 [ 2  3]]
M == 2 =>
 [[False False]
 [False False]
 [ True False]]
M > 2 =>
 [[False  True]
 [ True False]
 [False  True]]
M == v =>
 [[False  True]
 [False False]
 [ True  True]]


**Truco:** Cuando se trabaja con arrays, los equivalentes a `sum`, `all` y `any`, que se usaban para colecciones, son `np.sum`, `np.all` y `np.any`.

In [106]:
print(f"M =>\n {M}")
print(f"M > -10 =>\n {M > -10}")
print(f"np.all(M > -10) => {np.all(M > -10)}")
print(f"np.sum(M) =>\n {np.sum(M)}")

M =>
 [[-2  3]
 [ 4 -5]
 [ 2  3]]
M > -10 =>
 [[ True  True]
 [ True  True]
 [ True  True]]
np.all(M > -10) => True
np.sum(M) =>
 5


<span class="label label-info"><i class="fa fa-info-circle" aria-hidden="true"></i> Truco</span> El operador `*` es la multiplicación elemento a elemento, para la multiplicación de matrices, se usa `@`.

In [107]:
M = np.array([[-2, 3], [4, -5]])
print(f"M =>\n {M}")
print(f"M * M =>\n {M * M}")
print(f"M @ M =>\n {M @ M}")

M =>
 [[-2  3]
 [ 4 -5]]
M * M =>
 [[ 4  9]
 [16 25]]
M @ M =>
 [[ 16 -21]
 [-28  37]]


# Ejercicios de Autoevaluación

### Ejercicio 1
Dada una lista, ¿como podriamos invertirla? Aplica los mismos conceptos que vimos en el slicing de strings.

In [108]:
aList = [100, 200, 300, 400, 500]
aList = aList[::-1]
print(aList)

[500, 400, 300, 200, 100]


### Ejercicio 2
Crea una funcion que acepte como parametros una lista y un valor y que elimine el valor de la lista. Por ejemplo si la entrada es list1 = [5, 20, 15, 20, 25, 50, 20] y valor=20 la salida deberia ser [5, 15, 25, 50]

In [109]:
def delete_value(listValues, val):
   while val in listValues:
      listValues.remove(val)
   return listValues

def removeValue(sampleList, val):
   return [value for value in sampleList if value != val]

list1 = [5, 20, 15, 20, 25, 50, 20]
delete_value(list1, 20)
print(list1)

list1 = [5, 20, 15, 20, 25, 50, 20]
print(removeValue(list1, 20))

[5, 15, 25, 50]
[5, 15, 25, 50]


In [110]:
%%timeit
list1 = [5, 20, 15, 20, 25, 50, 20]
delete_value(list1, 20)

382 ns ± 5.69 ns per loop (mean ± std. dev. of 7 runs, 1,000,000 loops each)


In [111]:
%%timeit
list1 = [5, 20, 15, 20, 25, 50, 20]
removeValue(list1, 20)

479 ns ± 21.2 ns per loop (mean ± std. dev. of 7 runs, 1,000,000 loops each)


### Ejercicio 3
Dado el siguiente diccionario, ¿cómo accederias al valor indicado por "history"?

In [112]:
sampleDict = { 
   "class":{ 
      "student":{ 
         "name":"Mike",
         "marks":{ 
            "physics":70,
            "history":80
         }
      }
   }
}
# SOLUCION POSIBLE
print(sampleDict['class']['student']['marks']['history'])

80


### Ejercicio 4
Escribe una funcion que identifique si la llave (key) de un diccionario ya existe o no

In [113]:
#SOLUCION PROPUESTA
def is_key_present(dictionary, key):
  print(key in dictionary)

d = {1: 10, 2: 20, 3: 30, 4: 40, 5: 50, 6: 60}

is_key_present(d, 5)
is_key_present(d, 9)
# Esta otra función aquí trabaja con la variable global `d`, por lo cuál debe existir antes de llamarla
def is_key_present(x):
  if x in d:
      print('Key is present in the dictionary')
  else:
      print('Key is not present in the dictionary')
is_key_present(5)
is_key_present(9)

True
False
Key is present in the dictionary
Key is not present in the dictionary


### Ejercicio 5
Escribe una funcion que reciba una lista como parametro y calcula la suma de todos sus elementos.

In [114]:
#SOLUCION PROPUESTA
def sum_list(items):
    return sum(items)
print(sum_list([1,2,-8]))

-5


### Ejercicio 6
Escribe una funcion que dada una lista que contiene strings, calcule el numero de esos strings que tiene un longitud mayor de dos y ademas que la primera letra es igual a la ultima letra. Por ejemplo si el parametro de entrada fuera ['abc', 'xyz', 'aba', '1221'] la salida deberia ser 2.

In [115]:
#SOLUCION PROPUESTA
def check_list(list_strings):
  counter = 0
  for element in list_strings:
      if len(element) > 2 and element[0] == element[-1]:
          counter += 1
  return counter

print(check_list(['abc', 'xyz', 'aba', '1221']))

2


### Ejercicio 7
Escribe un programa que elimine los duplicados de una lista y devuelva la lista sin duplicados.

In [121]:
# Convierto lista en conjunto para eliminar duplicados, y luego vuelvo a convertir en lista
def remove_duplicates(list_numbers):
  return sorted((list(set(list_numbers))))

a = [10,20,30,20,10,50,60,40,80,50,40]

print(remove_duplicates(a))


dup_items = []
uniq_items = []
# Otra forma de hacerlo
for x in a:
    if x not in dup_items:
        uniq_items.append(x)
        # El método insert() inserta el objeto x en la posición dada, desplazando los elementos existentes a la derecha.
        dup_items.insert(0,x)

print(dup_items)

[10, 20, 30, 40, 50, 60, 80]
[80, 40, 60, 50, 30, 20, 10]


### Ejercicio 8
Escribir un programa que almacene en una lista los siguientes precios, 50, 75, 46, 22, 80, 65, 8, y muestre por pantalla el menor y el mayor de los precios.

In [117]:
#SOLUCION PROPUESTA
price_list = [50, 75, 46, 22, 80, 65, 8]
print(f"El mínimo precio es {min(price_list)} y el máximo precio es {max(price_list)}")

El mínimo precio es 8 y el máximo precio es 80


### Ejercicio 9
Escribir un programa que almacene las asignaturas de un curso (por ejemplo Visualizacion, IA, DL, Estadistica y Series) 
en una lista, pregunte al usuario la nota que ha sacado en cada asignatura, las almacene en una lista de notas, y después las muestre por pantalla con el mensaje: 

"En *curso* has sacado *nota*."

In [118]:
#SOLUCION PROPUESTA
subjects = ["Matemáticas", "Física", "Química", "Historia", "Lengua"]
scores = []
for subject in subjects:
    score = input("¿Qué nota has sacado en " + subject + "?")
    scores.append(score)
for i in range(len(subjects)):
    print("En " + subjects[i] + " has sacado " + scores[i])

En Matemáticas has sacado 4
En Física has sacado 4.5
En Química has sacado 3.8
En Historia has sacado 4563
En Lengua has sacado 152
